server:
  port: 8080
  mode: debug

database:
  host: localhost
  port: 3306
  username: user
  password: 123456
  database: user

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  poolSize: 10

log:
  level: info
  path: logs 